version: "3"
services:
  database:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
  webapp:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    container_name: utility_server
    environment:
      TZ: Asia/Seoul
    depends_on:
      - database